server:
  port: 5000
spring:
  application:
    name: crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.45.150
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

aliyun:
  oss:
    access-key-id: LTAI4G8wkHaTXxQgNsF6jmva
    access-key-secret: aqhlfvBEnIiZKbsaqYKCFRrTzZnGjb
    bucket-domain: http://qicheng2020.oss-cn-beijing.aliyuncs.com
    bucket-name: qicheng2020
    end-point: oss-cn-beijing.aliyuncs.com
    #https://qicheng2020.oss-cn-beijing.aliyuncs.com/images/2.jpg